"""Add GeneratedVideo model

Revision ID: 029
Revises: 
Create Date: 2025-12-08 08:55:56.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '029'
down_revision = '028'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('video_type', sa.String(length=50), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('generation_mode', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=True),
    sa.Column('motion_intensity', sa.String(length=20), nullable=True),
    sa.Column('source_image_url', sa.Text(), nullable=True),
    sa.Column('slides_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_generation_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['generated_content.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_videos_campaign_id', 'generated_videos', ['campaign_id'], unique=False)
    op.create_index('ix_generated_videos_content_id', 'generated_videos', ['content_id'], unique=False)
    op.create_index('ix_generated_videos_status', 'generated_videos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generated_videos_status', table_name='generated_videos')
    op.drop_index('ix_generated_videos_content_id', table_name='generated_videos')
    op.drop_index('ix_generated_videos_campaign_id', table_name='generated_videos')
    op.drop_table('generated_videos')
    # ### end Alembic commands ###
